[project]
name = "shepherd-nova"
version = "0.1.0"
description = "Public instance of the Shepherd Testbed"
requires-python = ">=3.12"
dependencies = [
    "sphinx>=7.0.0",
    "sphinxawesome-theme",
    "sphinx-sitemap",
    "myst-parser",
    "docutils",
    "shepherd-data",
    "pre-commit",
]
