name: QA-Tests

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Run Pre-Commit Tests 🧪
        uses: j178/prek-action@v1
